# Configure the AWS provider for the ap-northeast-2 region
provider "aws" {
  region = "ap-northeast-2"
}

# Reference the existing CloudWatch log group
data "aws_cloudwatch_log_group" "eks_cluster_log_group" {
  name = "/aws/eks/0202_test/cluster"
}

# Create a CloudWatch Logs Metric Filter to detect sensitive patterns in log events
resource "aws_cloudwatch_log_metric_filter" "sensitive_data_detection" {
  name           = "sensitive-data-detection"
  pattern        = "[version, account, @timestamp, @message, @ingestion_time, arn, aws_request_id, aws_function_name, aws_function_version, aws_log_group_name, aws_log_stream_name, aws_region, aws_service, aws_service_name, aws_session_name, aws_source_ip, aws_user_agent, aws_user_name, aws_vpc_id, aws_account_id, aws_access_key_id, aws_secret_access_key, aws_session_token, aws_security_token, aws_credentials_expiration, aws_role_arn, aws_role_session_name, aws_role_session_expiration, aws_role_duration_seconds, aws_role_last_used_date, aws_role_last_used_region, aws_role_last_used_service, aws_role_session_start_time, aws_role_session_end_time, aws_role_session_duration, aws_role_session_name, aws_role_session_expiration, aws_role_session_duration, aws_role_session_start_time, aws_role_session_end_time, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_used_service, aws_role_session_last_used_date, aws_role_session_last_used_region, aws_role_session_last_use